# Full list of versions available here: https://registry.hub.docker.com/_/node/tags/manage/\n' +
FROM node:boron

# Add repository files to container

#Start: Main Repository
ADD "./package.json" "/app/package.json"
WORKDIR /app
RUN npm install

ADD "./.git" "/app/.git"
ADD "./.gitmodules" "/app/.gitmodules"
RUN git submodule update --init --recursive
#End

WORKDIR /app
ADD "./" "/app"
# Open up ports on the container
EXPOSE 3000

# Command to start the app
CMD npm run test
