# Full list of versions available here: https://registry.hub.docker.com/_/node/tags/manage/\n' +
FROM node:argon

# Add repository files to container

#Start: Main Repository
ADD ["./octobear", "/octobear"]
WORKDIR /octobear
RUN git submodule update --init --recursive
RUN npm install
#End

WORKDIR /octobear

# Open up ports on the container
EXPOSE 3000

# Command to start the app
CMD npm run test
